obstacle_range: 2.5
raytrace_range: 4.0

footprint: [[0.25,0.25],[0.25,-0.25],[-0.25,-0.25],[-0.25,0.25]]
inflation_radius: 0.25

observation_sources: point_cloud_sensor laser_scan_sensor_left laser_scan_sensor_right laser_scan_sensor_back

point_cloud_sensor: {sensor_frame: realsense_optical_link, data_type: PointCloud2, topic: /realsense/depth/points , marking: true, clearing: true, min_obstacle_height: 0.1}

laser_scan_sensor_left: {sensor_frame: left_ultrasonic_link, data_type: LaserScan, topic: ultrasonic/left, marking: true, clearing: true}

laser_scan_sensor_right: {sensor_frame: right_ultrasonic_link, data_type: LaserScan, topic: ultrasonic/right, marking: true, clearing: true}

laser_scan_sensor_back: {sensor_frame: back_ultrasonic_link, data_type: LaserScan, topic: ultrasonic/back, marking: true, clearing: true}